### PR TITLE
add examples of invalid files to test the amber file validation code in alchemlyb

### PR DESCRIPTION
**Pull request by shuail**

### CODE REVIEW

**Comment by orbeckst** [comment]
@shuail I think your Amber parser can read bzipped files (or at least it will, once you use `anyopen()`). Could you add these files in bzip2-format, i.e., just `bzip2 invalid/*.out` and update the description and `setup.py` to include them.

This will keep the package size small.

**Comment by dotsdl** [comment]
I don't believe the original *.out files were removed. They are present alongside the *.bz2 files. @orbeckst is the best way to remove these to use a `git rm`? I know there are ways of removing files from the git history, but not sure if that's a good idea for us here.

**Comment by orbeckst** [comment]
oops, this eluded me. Sorry.

Definitely `git rm`. I can unprotect master and force-push a rewritten history but that's not worth the hassle. They are not enormously big, just 740k uncompressed. It would have been nicer if I had caught it when I rewrote the history for the PR but there's not much harm to keep them inside git's history. If you like to do a quick PR? (I am heading home now...)

**Comment by shuail** [comment]
@orbeckst @dotsdl oops, sorry, it seems the last commit did not deliver the jobs as it supposed to be... I could push another small PR to make the changes, do you want me to do that? @orbeckst

**Comment by orbeckst** [comment]
Make a new PR where you remove the uncompressed outfiles for invalid. Thanks. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Pull request merged**
