### PR TITLE
Updating free energy file name

### PR DESCRIPTION
**Pull request by msoroush**
Fix to the issue #35

### CODE REVIEW

**Comment by orbeckst** [comment]
Can you please create this PR against the latest master? It should only contain 91a706a3d4903d18c042c9b89c28d2006aaa07f6

Depending on how you configured your checked out copy of your fork, `git pull` from the master. I would do
```
git remote add upstream https://github.com/alchemistry/alchemtest.git
git pull upstream master
git push
```

In the future you can then just say `git pull upstream master`. 

In the future I would also create branches for pull requests so that you can easily keep your master in sync with the upstream master.

**Comment by msoroush** [comment]
> Can you please create this PR against the latest master? It should only contain [91a706a](https://github.com/alchemistry/alchemtest/commit/91a706a3d4903d18c042c9b89c28d2006aaa07f6)
> 
> Depending on how you configured your checked out copy of your fork, `git pull` from the master. I would do
> 
> ```
> git remote add upstream https://github.com/alchemistry/alchemtest.git
> git pull upstream master
> git push
> ```
> 
> In the future you can then just say `git pull upstream master`.
> 
> In the future I would also create branches for pull requests so that you can easily keep your master in sync with the upstream master.

Sorry about that. I forgot to update my fork. Is this works or you want me to make a new branch and create new PR?

**Comment by dotsdl** [comment]
Hey @msoroush! I think a new PR may be the easiest path here. Your master branch may now have a different history than the master branch here, so you may have to force git to overwrite your branch with this one when you pull, which I think you can do with a `--force` flag. If that fails, you could try deleting your local master branch first with `git branch -D master`:

```
git checkout -b tmp   #  create and switch to branch `tmp`
git branch -D master # delete master branch

# get upstream master
git remote add upstream https://github.com/alchemistry/alchemtest.git
git pull upstream master

# switch to upstream/master (detached HEAD state)
git checkout upstream/master

# create new `master` branch based on upstream master
git checkout -b master

# create and switch to your own feature branch
git checkout -b alchemtest-35
```
Then add your changes, commit them, push them to a new `alchemtest-35` branch on your Github repo, and open a PR against master on this repo.

**Comment by msoroush** [comment]
@dotsdl sorry for the headache. I create a new PR.

**Comment by orbeckst** [comment]
Closing because superseded by #39

**Pull request closed without merging**
