### PR TITLE
updated versioneer files

### LINKED ISSUE #70: Do we have a possible undefined variable in `_version`?
I noticed in `_version.py` we have at line 89 a variable `dispcmd` that is not defined inside of the `except` block, as it was defined inside the `try` block. Should we just move line 77 up before the `try` statement?

### PR DESCRIPTION
**Pull request by orbeckst**
- fix #70 
- only compatible with Python 3.7+
- used versioneer 0.26
- still uses vendor mode

### CODE REVIEW

**Comment by orbeckst** [comment]
WARNING: **This PR can only be merged if we adopt NEP29 and restrict alchemtest to python ≥ 3.7.**

**Comment by orbeckst** [comment]
This PR should work after the NEP29 PR #76 is merged.

**Comment by orbeckst** [comment]
RTD failed a Python 3.7 build with
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/alchemtest/checkouts/73
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-xffisvuw/setup.py", line 12, in <module>
        import versioneer
      File "/tmp/pip-req-build-xffisvuw/versioneer.py", line 409
        LONG_VERSION_PY: Dict[str, str] = {}
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-xffisvuw/
You are using pip version 10.0.1, however version 20.3.4 is available.
```
It looks as if there's some typing in the new `versioneer.py` file that's not compatible with Python 3.7. If this is the case then this PR cannot be merged until we drop 3.7.

**Comment by orbeckst** [comment]
Interesting: RTD does not support Python > 3.8
```
Error

Problem in your project's configuration. Invalid "python.version": expected one of (2, 2.7, 3, 3.5, 3.6, 3.7, 3.8, pypy3.5), got 3.9
```

**Comment by orbeckst** [comment]
Well, RTD does not like the new versioneer file
```
Processing /home/docs/checkouts/readthedocs.org/user_builds/alchemtest/checkouts/73
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-hsj06cht/setup.py", line 12, in <module>
        import versioneer
      File "/tmp/pip-req-build-hsj06cht/versioneer.py", line 409
        LONG_VERSION_PY: Dict[str, str] = {}
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-hsj06cht/
You are using pip version 10.0.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by xiki-tempula** [comment]
I think we should just use the old versioneer file and only update it if it fails to do what we want it to do.

**Comment by orbeckst** [comment]
Fair enough, we’ll just leave the PR open.

**Comment by orbeckst** [comment]
We now use versioningit #93

**Pull request closed without merging**
