### PR TITLE
NEP29

### PR DESCRIPTION
**Pull request by xiki-tempula**
Remove support for py<3.7.

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
Please update the documentation, too.

**Comment by xiki-tempula** [comment]
@orbeckst @DrDomenicoMarson is using pathlib for the path related operations in https://github.com/alchemistry/alchemtest/pull/71, so it is good to deprecate the versions that do not support pathlib.

I wonder when you say documentation, what do you mean? I have searched the 2.7 and cannot find more hits.

**Comment by orbeckst** [comment]
Add a note to the docs that states that we follow NEP29, pretty much the same as in the alchemlyb docs that I linked in #77

**Comment by xiki-tempula** [comment]
@orbeckst Right. I have added the secion to index.rst saying that we will adopt NEP29 from 0.8.0

**Review by orbeckst — APPROVED** [review]

**Pull request merged**
